language: node_js

node_js:
  - "6"

cache:
  yarn: true

install:
  - yarn install

script:
  - yarn run flow
  - yarn run test
  - yarn run build

deploy:
  - provider: npm
    api_key: "$NPM_TOKEN"
    email: "$NPM_EMAIL"
    skip_cleanup: true
    on:
      tags: true
