language: node_js

node_js:
  - "6"

cache:
  yarn: true

install:
  - yarn install

script:
  - yarn run flow
  - yarn run test:coveralls
  - yarn run build

before_deploy:
  - npm version -f --no-git-tag-version $(git describe --tag);

deploy:
  - provider: npm
    api_key: "$NPM_TOKEN"
    email: "$NPM_EMAIL"
    skip_cleanup: true
    on:
      tags: true
